# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200309_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ticketID',
            field=models.IntegerField(default=0),
        ),
    ]
