# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-24 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cash_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='points_available',
            field=models.IntegerField(default=0),
        ),
    ]
