# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-19 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200324_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forum_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
