# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-21 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_forum_upvotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='points_available',
            field=models.IntegerField(default=5),
        ),
    ]
