# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-20 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ticketID',
            new_name='forumID',
        ),
    ]
