# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-08 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20200307_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
