# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-19 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
