# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-29 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
